# Form implementation generated from reading ui file 'GDAdmin.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 592)
        MainWindow.setStyleSheet("QMainWindow, QWidget#centralwidget {\n"
"  background-color: #F7F5F0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, -1, 1001, 541))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 541))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QFrame(parent=self.horizontalLayoutWidget)
        self.sidebar.setBaseSize(QtCore.QSize(220, 0))
        self.sidebar.setStyleSheet("QFrame {\n"
"    background-color: #1A2A4A;\n"
"  border-right: 2px solid #C9A84C;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"  color: #D0C9B8;\n"
"  font-size: 13px;\n"
"  text-align: left;\n"
"  padding: 11px 20px;\n"
"  border: none;\n"
"  border-left: 3px solid transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #223259;\n"
"  color: #FFFFFF;\n"
"  border-left: 3px solid #C9A84C;\n"
"}\n"
"QPushButton:checked, QPushButton:pressed {\n"
"  background-color: #223259;\n"
"  color: #FFFFFF;\n"
"  border-left: 3px solid #C9A84C;\n"
"  font-weight: bold;\n"
"}\n"
"")
        self.sidebar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=self.sidebar)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 191, 82))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #12213A;\n"
"  color: #C9A84C;\n"
"  font-size: 15px;\n"
"  font-weight: bold;\n"
"  padding: 14px 16px;\n"
"  border-bottom: 1px solid #C9A84C;")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(parent=self.sidebar)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 80, 191, 408))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.BtnDashBoard = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.BtnDashBoard.setFont(font)
        self.BtnDashBoard.setObjectName("BtnDashBoard")
        self.verticalLayout_6.addWidget(self.BtnDashBoard)
        self.BtnRoom = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.BtnRoom.setFont(font)
        self.BtnRoom.setObjectName("BtnRoom")
        self.verticalLayout_6.addWidget(self.BtnRoom)
        self.BtnCustomer = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.BtnCustomer.setFont(font)
        self.BtnCustomer.setObjectName("BtnCustomer")
        self.verticalLayout_6.addWidget(self.BtnCustomer)
        self.BtnStaff = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.BtnStaff.setFont(font)
        self.BtnStaff.setObjectName("BtnStaff")
        self.verticalLayout_6.addWidget(self.BtnStaff)
        self.BtnAddRoom = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.BtnAddRoom.setFont(font)
        self.BtnAddRoom.setObjectName("BtnAddRoom")
        self.verticalLayout_6.addWidget(self.BtnAddRoom)
        self.BtnSerVice = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.BtnSerVice.setFont(font)
        self.BtnSerVice.setObjectName("BtnSerVice")
        self.verticalLayout_6.addWidget(self.BtnSerVice)
        self.BtnReport = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.BtnReport.setFont(font)
        self.BtnReport.setObjectName("BtnReport")
        self.verticalLayout_6.addWidget(self.BtnReport)
        self.horizontalLayout.addWidget(self.sidebar)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(190, 0, 801, 541))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Main = QtWidgets.QFrame(parent=self.horizontalLayoutWidget_2)
        self.Main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Main.setObjectName("Main")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.Main)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.Header.setBaseSize(QtCore.QSize(0, 60))
        self.Header.setStyleSheet("background-color: #FFFFFF;\n"
"  border-bottom: 2px solid #C9A84C;")
        self.Header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.Header)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 0, 271, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #1A2A4A;\n"
"  font-size: 16px;\n"
"  font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.Header)
        self.label_3.setGeometry(QtCore.QRect(580, 0, 71, 49))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #6B7896;\n"
"  font-size: 13px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.Header)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(650, 0, 95, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Btnlog = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.Btnlog.setStyleSheet("QPushButton {\n"
"  background-color: #1A2A4A;\n"
"  color: #FFFFFF;\n"
"  border: none;\n"
"  border-radius: 6px;\n"
"  padding: 6px 16px;\n"
"  font-size: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #C9A84C;\n"
"  color: #1A2A4A;\n"
"}")
        self.Btnlog.setObjectName("Btnlog")
        self.horizontalLayout_4.addWidget(self.Btnlog)
        self.verticalLayout.addWidget(self.Header)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.Main)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 50, 801, 491))
        self.stackedWidget.setStyleSheet("background-color: #F7F5F0;\n"
"")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.page)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 801, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.verticalLayoutWidget_3)
        self.widget_2.setObjectName("widget_2")
        self.frame = QtWidgets.QFrame(parent=self.widget_2)
        self.frame.setGeometry(QtCore.QRect(30, 10, 171, 111))
        self.frame.setStyleSheet("background-color: #EAF2FB;\n"
"  border: 1px solid #B5D4F4;\n"
"  border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #1A2B4A;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 12px;")
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_2.setGeometry(QtCore.QRect(220, 10, 171, 111))
        self.frame_2.setStyleSheet("background-color: #FDECEA;\n"
"  border: 1px solid #F7C1C1;\n"
"  border-radius: 10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #1A2B4A;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 12px;")
        self.label_5.setObjectName("label_5")
        self.frame_3 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_3.setGeometry(QtCore.QRect(410, 10, 171, 111))
        self.frame_3.setStyleSheet(" background-color: #FFF3CD;\n"
"  border: 1px solid #FAC775;\n"
"  border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(40, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #1A2B4A;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 12px;")
        self.label_6.setObjectName("label_6")
        self.frame_4 = QtWidgets.QFrame(parent=self.widget_2)
        self.frame_4.setGeometry(QtCore.QRect(600, 10, 171, 111))
        self.frame_4.setStyleSheet("background-color: #E8F5E9;\n"
"  border: 1px solid #C0DD97;\n"
"  border-radius: 10px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(30, 30, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #1A2B4A;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 12px;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.widget_2)
        self.placeholder = QtWidgets.QFrame(parent=self.page)
        self.placeholder.setGeometry(QtCore.QRect(0, 180, 791, 181))
        self.placeholder.setBaseSize(QtCore.QSize(0, 200))
        self.placeholder.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.placeholder.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.placeholder.setObjectName("placeholder")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.page_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(110, 20, 571, 41))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.BtnAddRoom_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.BtnAddRoom_2.setStyleSheet("QPushButton {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton: {\n"
"    background-color: #223259;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0F1B30;\n"
"}")
        self.BtnAddRoom_2.setObjectName("BtnAddRoom_2")
        self.horizontalLayout_9.addWidget(self.BtnAddRoom_2)
        self.BtnEditRoom = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.BtnEditRoom.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #1A2B4A;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAF2FB;\n"
"    border-color: #C9A84C;\n"
"    color: #C9A84C;\n"
"}")
        self.BtnEditRoom.setObjectName("BtnEditRoom")
        self.horizontalLayout_9.addWidget(self.BtnEditRoom)
        self.BtnDeleteRoom = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.BtnDeleteRoom.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #A32D2D;\n"
"    border: 1.5px solid #A32D2D;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FDECEA;\n"
"}")
        self.BtnDeleteRoom.setObjectName("BtnDeleteRoom")
        self.horizontalLayout_9.addWidget(self.BtnDeleteRoom)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.Search = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.Search.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.Search.setObjectName("Search")
        self.horizontalLayout_9.addWidget(self.Search)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.tableWidget_6 = QtWidgets.QTableWidget(parent=self.page_2)
        self.tableWidget_6.setGeometry(QtCore.QRect(10, 60, 781, 411))
        self.tableWidget_6.setStyleSheet("QTableWidget, QTableView {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F0EDE6;\n"
"    border: 1px solid #D3CECC;\n"
"    border-radius: 6px;\n"
"    gridline-color: #E5E0D8;\n"
"    selection-background-color: #EAF2FB;\n"
"    selection-color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item, QTableView::item {\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QTableWidget::item:selected, QTableView::item:selected {\n"
"    background-color: #D6E8F7;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 8px 10px;\n"
"    border: none;\n"
"    border-right: 1px solid #223259;\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-right: none;\n"
"}\n"
"")
        self.tableWidget_6.setRowCount(0)
        self.tableWidget_6.setColumnCount(4)
        self.tableWidget_6.setObjectName("tableWidget_6")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        self.tableWidget_6.horizontalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(parent=self.page_3)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(50, 20, 701, 39))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.BtnAddRoom_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_10)
        self.BtnAddRoom_3.setStyleSheet("QPushButton {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton: {\n"
"    background-color: #223259;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0F1B30;\n"
"}")
        self.BtnAddRoom_3.setObjectName("BtnAddRoom_3")
        self.horizontalLayout_11.addWidget(self.BtnAddRoom_3)
        self.BtnEditRoom_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_10)
        self.BtnEditRoom_2.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #1A2B4A;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAF2FB;\n"
"    border-color: #C9A84C;\n"
"    color: #C9A84C;\n"
"}")
        self.BtnEditRoom_2.setObjectName("BtnEditRoom_2")
        self.horizontalLayout_11.addWidget(self.BtnEditRoom_2)
        self.BtnDeleteRoom_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_10)
        self.BtnDeleteRoom_2.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #A32D2D;\n"
"    border: 1.5px solid #A32D2D;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FDECEA;\n"
"}")
        self.BtnDeleteRoom_2.setObjectName("BtnDeleteRoom_2")
        self.horizontalLayout_11.addWidget(self.BtnDeleteRoom_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.Search_2 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_10)
        self.Search_2.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.Search_2.setObjectName("Search_2")
        self.horizontalLayout_11.addWidget(self.Search_2)
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.page_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 70, 781, 411))
        self.tableWidget_2.setStyleSheet("QTableWidget, QTableView {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F0EDE6;\n"
"    border: 1px solid #D3CECC;\n"
"    border-radius: 6px;\n"
"    gridline-color: #E5E0D8;\n"
"    selection-background-color: #EAF2FB;\n"
"    selection-color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item, QTableView::item {\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QTableWidget::item:selected, QTableView::item:selected {\n"
"    background-color: #D6E8F7;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 8px 10px;\n"
"    border: none;\n"
"    border-right: 1px solid #223259;\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-right: none;\n"
"}\n"
"")
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(parent=self.page_4)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(120, 20, 541, 39))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.BtnAddRoom_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_11)
        self.BtnAddRoom_4.setStyleSheet("QPushButton {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton: {\n"
"    background-color: #223259;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0F1B30;\n"
"}")
        self.BtnAddRoom_4.setObjectName("BtnAddRoom_4")
        self.horizontalLayout_12.addWidget(self.BtnAddRoom_4)
        self.BtnEditRoom_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_11)
        self.BtnEditRoom_3.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #1A2B4A;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAF2FB;\n"
"    border-color: #C9A84C;\n"
"    color: #C9A84C;\n"
"}")
        self.BtnEditRoom_3.setObjectName("BtnEditRoom_3")
        self.horizontalLayout_12.addWidget(self.BtnEditRoom_3)
        self.BtnDeleteRoom_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_11)
        self.BtnDeleteRoom_3.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #A32D2D;\n"
"    border: 1.5px solid #A32D2D;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FDECEA;\n"
"}")
        self.BtnDeleteRoom_3.setObjectName("BtnDeleteRoom_3")
        self.horizontalLayout_12.addWidget(self.BtnDeleteRoom_3)
        self.BtnResetPass = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_11)
        self.BtnResetPass.setStyleSheet("QPushButton {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton: {\n"
"    background-color: #223259;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0F1B30;\n"
"}")
        self.BtnResetPass.setObjectName("BtnResetPass")
        self.horizontalLayout_12.addWidget(self.BtnResetPass)
        self.tableWidget_3 = QtWidgets.QTableWidget(parent=self.page_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 70, 781, 411))
        self.tableWidget_3.setStyleSheet("QTableWidget, QTableView {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F0EDE6;\n"
"    border: 1px solid #D3CECC;\n"
"    border-radius: 6px;\n"
"    gridline-color: #E5E0D8;\n"
"    selection-background-color: #EAF2FB;\n"
"    selection-color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item, QTableView::item {\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QTableWidget::item:selected, QTableView::item:selected {\n"
"    background-color: #D6E8F7;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 8px 10px;\n"
"    border: none;\n"
"    border-right: 1px solid #223259;\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-right: none;\n"
"}\n"
"")
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setObjectName("tableWidget_3")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.page_4)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.page_6)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 781, 461))
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid #D3CECC;\n"
"    border-radius: 0 6px 6px 6px;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #E8E0CE;\n"
"    color: #6B7896;\n"
"    border: 1px solid #D3CECC;\n"
"    border-bottom: none;\n"
"    border-radius: 5px 5px 0 0;\n"
"    padding: 8px 20px;\n"
"    font-size: 13px;\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    border-color: #1A2B4A;\n"
"}\n"
"\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #D3CECC;\n"
"    color: #1A2B4A;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget_3 = QtWidgets.QWidget(parent=self.tab)
        self.widget_3.setGeometry(QtCore.QRect(20, 10, 731, 51))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(parent=self.widget_3)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(40, 10, 181, 39))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 17px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(parent=self.widget_3)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(300, 10, 381, 36))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.CbKhach = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_14)
        self.CbKhach.setStyleSheet("\n"
"QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"    min-width: 240px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.CbKhach.setObjectName("CbKhach")
        self.horizontalLayout_15.addWidget(self.CbKhach)
        self.widget_4 = QtWidgets.QWidget(parent=self.tab)
        self.widget_4.setGeometry(QtCore.QRect(20, 70, 731, 51))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(parent=self.widget_4)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(40, 10, 181, 39))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 17px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(parent=self.widget_4)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(300, 10, 381, 36))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.CbPhong = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_16)
        self.CbPhong.setStyleSheet("\n"
"QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"    min-width: 240px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.CbPhong.setObjectName("CbPhong")
        self.horizontalLayout_17.addWidget(self.CbPhong)
        self.widget_5 = QtWidgets.QWidget(parent=self.tab)
        self.widget_5.setGeometry(QtCore.QRect(20, 130, 731, 51))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(parent=self.widget_5)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(40, 10, 181, 39))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_10 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 17px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_18.addWidget(self.label_10)
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(parent=self.widget_5)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(300, 10, 381, 34))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.DateCheckIn = QtWidgets.QDateEdit(parent=self.horizontalLayoutWidget_18)
        self.DateCheckIn.setStyleSheet("QDateEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 5px 8px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    border: none;\n"
"    width: 22px;\n"
"}\n"
"")
        self.DateCheckIn.setObjectName("DateCheckIn")
        self.horizontalLayout_19.addWidget(self.DateCheckIn)
        self.widget_6 = QtWidgets.QWidget(parent=self.tab)
        self.widget_6.setGeometry(QtCore.QRect(20, 190, 731, 51))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(parent=self.widget_6)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(40, 10, 181, 40))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_11 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 17px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_20.addWidget(self.label_11)
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(parent=self.widget_6)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(300, 10, 381, 34))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.DateCheckOut = QtWidgets.QDateEdit(parent=self.horizontalLayoutWidget_20)
        self.DateCheckOut.setStyleSheet("QDateEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 5px 8px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    border: none;\n"
"    width: 22px;\n"
"}\n"
"")
        self.DateCheckOut.setObjectName("DateCheckOut")
        self.horizontalLayout_21.addWidget(self.DateCheckOut)
        self.widget_7 = QtWidgets.QWidget(parent=self.tab)
        self.widget_7.setGeometry(QtCore.QRect(20, 250, 731, 121))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayoutWidget_21 = QtWidgets.QWidget(parent=self.widget_7)
        self.horizontalLayoutWidget_21.setGeometry(QtCore.QRect(40, 10, 181, 40))
        self.horizontalLayoutWidget_21.setObjectName("horizontalLayoutWidget_21")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_21)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_12 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_21)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 17px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_22.addWidget(self.label_12)
        self.horizontalLayoutWidget_22 = QtWidgets.QWidget(parent=self.widget_7)
        self.horizontalLayoutWidget_22.setGeometry(QtCore.QRect(300, 10, 381, 107))
        self.horizontalLayoutWidget_22.setObjectName("horizontalLayoutWidget_22")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_22)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.TextNote = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_22)
        self.TextNote.setStyleSheet("QTextEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 8px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.TextNote.setObjectName("TextNote")
        self.horizontalLayout_23.addWidget(self.TextNote)
        self.PustXacNhan = QtWidgets.QPushButton(parent=self.tab)
        self.PustXacNhan.setGeometry(QtCore.QRect(500, 380, 201, 41))
        self.PustXacNhan.setBaseSize(QtCore.QSize(0, 40))
        self.PustXacNhan.setStyleSheet("QPushButton {\n"
"    background-color: #C9A84C;\n"
"    color: #1A2B4A;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 9px 28px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E0BF6A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A88A35;\n"
"}")
        self.PustXacNhan.setObjectName("PustXacNhan")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(250, 10, 261, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget_5 = QtWidgets.QTableWidget(parent=self.tab_2)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 50, 751, 321))
        self.tableWidget_5.setStyleSheet("QTableWidget, QTableView {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F0EDE6;\n"
"    border: 1px solid #D3CECC;\n"
"    border-radius: 6px;\n"
"    gridline-color: #E5E0D8;\n"
"    selection-background-color: #EAF2FB;\n"
"    selection-color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item, QTableView::item {\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QTableWidget::item:selected, QTableView::item:selected {\n"
"    background-color: #D6E8F7;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 8px 10px;\n"
"    border: none;\n"
"    border-right: 1px solid #223259;\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-right: none;\n"
"}\n"
"")
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(5)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        self.tableWidget_5.horizontalHeader().setStretchLastSection(True)
        self.BtnTraPhong = QtWidgets.QPushButton(parent=self.tab_2)
        self.BtnTraPhong.setGeometry(QtCore.QRect(210, 380, 141, 41))
        self.BtnTraPhong.setObjectName("BtnTraPhong")
        self.BtnHuy = QtWidgets.QPushButton(parent=self.tab_2)
        self.BtnHuy.setGeometry(QtCore.QRect(420, 380, 111, 41))
        self.BtnHuy.setObjectName("BtnHuy")
        self.tabWidget.addTab(self.tab_2, "")
        self.stackedWidget.addWidget(self.page_6)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(parent=self.page_5)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(140, 20, 531, 39))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.BtnAddRoom_5 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_12)
        self.BtnAddRoom_5.setStyleSheet("QPushButton {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton: {\n"
"    background-color: #223259;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0F1B30;\n"
"}")
        self.BtnAddRoom_5.setObjectName("BtnAddRoom_5")
        self.horizontalLayout_13.addWidget(self.BtnAddRoom_5)
        self.BtnEditRoom_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_12)
        self.BtnEditRoom_4.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #1A2B4A;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EAF2FB;\n"
"    border-color: #C9A84C;\n"
"    color: #C9A84C;\n"
"}")
        self.BtnEditRoom_4.setObjectName("BtnEditRoom_4")
        self.horizontalLayout_13.addWidget(self.BtnEditRoom_4)
        self.BtnDeleteRoom_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_12)
        self.BtnDeleteRoom_4.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #A32D2D;\n"
"    border: 1.5px solid #A32D2D;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FDECEA;\n"
"}")
        self.BtnDeleteRoom_4.setObjectName("BtnDeleteRoom_4")
        self.horizontalLayout_13.addWidget(self.BtnDeleteRoom_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.Search_3 = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_12)
        self.Search_3.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.Search_3.setObjectName("Search_3")
        self.horizontalLayout_13.addWidget(self.Search_3)
        self.tableWidget_4 = QtWidgets.QTableWidget(parent=self.page_5)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 70, 781, 411))
        self.tableWidget_4.setStyleSheet("QTableWidget, QTableView {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F0EDE6;\n"
"    border: 1px solid #D3CECC;\n"
"    border-radius: 6px;\n"
"    gridline-color: #E5E0D8;\n"
"    selection-background-color: #EAF2FB;\n"
"    selection-color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item, QTableView::item {\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QTableWidget::item:selected, QTableView::item:selected {\n"
"    background-color: #D6E8F7;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 8px 10px;\n"
"    border: none;\n"
"    border-right: 1px solid #223259;\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-right: none;\n"
"}\n"
"")
        self.tableWidget_4.setRowCount(0)
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setObjectName("tableWidget_4")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.page_5)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.widget_8 = QtWidgets.QWidget(parent=self.page_7)
        self.widget_8.setGeometry(QtCore.QRect(10, 20, 781, 41))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayoutWidget_23 = QtWidgets.QWidget(parent=self.widget_8)
        self.horizontalLayoutWidget_23.setGeometry(QtCore.QRect(10, 0, 261, 41))
        self.horizontalLayoutWidget_23.setObjectName("horizontalLayoutWidget_23")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_23)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_13 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_23)
        self.label_13.setStyleSheet("color:black;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_24.addWidget(self.label_13)
        self.comboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_23)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #C9A84C;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 24px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #1A2B4A;\n"
"    selection-background-color: #EAF2FB;\n"
"    selection-color: #1A2B4A;\n"
"    color: #1A2B4A;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_24.addWidget(self.comboBox)
        self.horizontalLayoutWidget_24 = QtWidgets.QWidget(parent=self.widget_8)
        self.horizontalLayoutWidget_24.setGeometry(QtCore.QRect(280, 0, 181, 41))
        self.horizontalLayoutWidget_24.setObjectName("horizontalLayoutWidget_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_24)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_14 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_24)
        self.label_14.setStyleSheet("color:black;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_25.addWidget(self.label_14)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.horizontalLayoutWidget_24)
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 5px 8px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    border: none;\n"
"    width: 22px;\n"
"}\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_25.addWidget(self.dateEdit)
        self.horizontalLayoutWidget_25 = QtWidgets.QWidget(parent=self.widget_8)
        self.horizontalLayoutWidget_25.setGeometry(QtCore.QRect(470, 0, 191, 41))
        self.horizontalLayoutWidget_25.setObjectName("horizontalLayoutWidget_25")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_25)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_15 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_25)
        self.label_15.setStyleSheet("color:black;")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_26.addWidget(self.label_15)
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=self.horizontalLayoutWidget_25)
        self.dateEdit_2.setStyleSheet("QDateEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 5px 8px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    border: none;\n"
"    width: 22px;\n"
"}\n"
"")
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_26.addWidget(self.dateEdit_2)
        self.BtnXem = QtWidgets.QPushButton(parent=self.widget_8)
        self.BtnXem.setGeometry(QtCore.QRect(670, 10, 93, 28))
        self.BtnXem.setStyleSheet("QPushButton {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 7px 22px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #223259;\n"
"}\n"
"")
        self.BtnXem.setObjectName("BtnXem")
        self.FraChart = QtWidgets.QFrame(parent=self.page_7)
        self.FraChart.setGeometry(QtCore.QRect(20, 170, 771, 231))
        self.FraChart.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FraChart.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FraChart.setObjectName("FraChart")
        self.widget_10 = QtWidgets.QWidget(parent=self.page_7)
        self.widget_10.setGeometry(QtCore.QRect(220, 419, 331, 51))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayoutWidget_30 = QtWidgets.QWidget(parent=self.widget_10)
        self.horizontalLayoutWidget_30.setGeometry(QtCore.QRect(-1, 0, 331, 51))
        self.horizontalLayoutWidget_30.setObjectName("horizontalLayoutWidget_30")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_30)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.BtnExcel = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_30)
        self.BtnExcel.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #1A2B4A;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 7px 22px;\n"
"    font-size: 13px;\n"
"    min-width: 110px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E8F5E9;\n"
"    border-color: #3B6D11;\n"
"    color: #3B6D11;\n"
"}")
        self.BtnExcel.setObjectName("BtnExcel")
        self.horizontalLayout_31.addWidget(self.BtnExcel)
        self.BtnPDF = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_30)
        self.BtnPDF.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #A32D2D;\n"
"    border: 1.5px solid #A32D2D;\n"
"    border-radius: 5px;\n"
"    padding: 7px 22px;\n"
"    font-size: 13px;\n"
"    min-width: 110px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FDECEA;\n"
"}")
        self.BtnPDF.setObjectName("BtnPDF")
        self.horizontalLayout_31.addWidget(self.BtnPDF)
        self.widget_9 = QtWidgets.QWidget(parent=self.page_7)
        self.widget_9.setGeometry(QtCore.QRect(20, 70, 771, 91))
        self.widget_9.setObjectName("widget_9")
        self.frame_6 = QtWidgets.QFrame(parent=self.widget_9)
        self.frame_6.setGeometry(QtCore.QRect(60, 10, 171, 81))
        self.frame_6.setStyleSheet("background-color: #FDECEA;\n"
"  border: 1px solid #F7C1C1;\n"
"  border-radius: 10px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(20, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: #1A2B4A;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 12px;")
        self.label_17.setObjectName("label_17")
        self.frame_7 = QtWidgets.QFrame(parent=self.widget_9)
        self.frame_7.setGeometry(QtCore.QRect(300, 10, 191, 81))
        self.frame_7.setStyleSheet(" background-color: #FFF3CD;\n"
"  border: 1px solid #FAC775;\n"
"  border-radius: 10px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #1A2B4A;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 12px;")
        self.label_18.setObjectName("label_18")
        self.frame_8 = QtWidgets.QFrame(parent=self.widget_9)
        self.frame_8.setGeometry(QtCore.QRect(550, 10, 171, 81))
        self.frame_8.setStyleSheet("background-color: #E8F5E9;\n"
"  border: 1px solid #C0DD97;\n"
"  border-radius: 10px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_19.setGeometry(QtCore.QRect(20, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: #1A2B4A;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    padding: 12px;")
        self.label_19.setObjectName("label_19")
        self.stackedWidget.addWidget(self.page_7)
        self.horizontalLayout_2.addWidget(self.Main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1001, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "🏨 HOTEL ADMIN"))
        self.BtnDashBoard.setText(_translate("MainWindow", "🏠 DashBoard"))
        self.BtnRoom.setText(_translate("MainWindow", "🛏 Quản Lý Phòng"))
        self.BtnCustomer.setText(_translate("MainWindow", "👥 Khách Hàng"))
        self.BtnStaff.setText(_translate("MainWindow", "👨‍💼 Nhân Viên"))
        self.BtnAddRoom.setText(_translate("MainWindow", "📅 Đặt Phòng"))
        self.BtnSerVice.setText(_translate("MainWindow", "🧾 Dịch Vụ"))
        self.BtnReport.setText(_translate("MainWindow", "📊 Thống Kê"))
        self.label_2.setText(_translate("MainWindow", "Quản Lý Phòng Khách Sạn"))
        self.label_3.setText(_translate("MainWindow", "Admin"))
        self.Btnlog.setText(_translate("MainWindow", "Đăng xuất"))
        self.label_4.setText(_translate("MainWindow", "Tổng Phòng"))
        self.label_5.setText(_translate("MainWindow", "Đang Thuê"))
        self.label_6.setText(_translate("MainWindow", "Khách"))
        self.label_7.setText(_translate("MainWindow", "Doanh Thu"))
        self.BtnAddRoom_2.setText(_translate("MainWindow", "➕ Thêm"))
        self.BtnEditRoom.setText(_translate("MainWindow", "✏️ Sửa"))
        self.BtnDeleteRoom.setText(_translate("MainWindow", "🗑 Xóa"))
        self.Search.setText(_translate("MainWindow", "🔍 Tìm Phòng"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã Phòng"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Loại Phòng"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Giá Tiền"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Trạng Thái"))
        self.BtnAddRoom_3.setText(_translate("MainWindow", "➕ Thêm"))
        self.BtnEditRoom_2.setText(_translate("MainWindow", "✏️ Sửa"))
        self.BtnDeleteRoom_2.setText(_translate("MainWindow", "🗑 Xóa"))
        self.Search_2.setText(_translate("MainWindow", "🔍 Tìm Khách Hàng"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã Khách Hàng"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên Khách Hàng"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SDT"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CCCD"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ngày tạo"))
        self.BtnAddRoom_4.setText(_translate("MainWindow", "➕ Thêm"))
        self.BtnEditRoom_3.setText(_translate("MainWindow", "✏️ Sửa"))
        self.BtnDeleteRoom_3.setText(_translate("MainWindow", "🗑 Xóa"))
        self.BtnResetPass.setText(_translate("MainWindow", "Đặt lại mật khẩu"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã Nhân Viên"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên Nhân Viên"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "UserName"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SDT"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Vai Trò"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Trạng Thái"))
        self.label_8.setText(_translate("MainWindow", "Khách Hàng"))
        self.label_9.setText(_translate("MainWindow", "Phòng"))
        self.label_10.setText(_translate("MainWindow", "Ngày Nhận"))
        self.label_11.setText(_translate("MainWindow", "Ngày Trả"))
        self.label_12.setText(_translate("MainWindow", "Ghi Chú"))
        self.PustXacNhan.setText(_translate("MainWindow", "Xác Nhận Đặt Phòng"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Đặt Phòng"))
        self.lineEdit.setText(_translate("MainWindow", "🔍 Tìm kiếm"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã Khách Hàng"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên Khách Hàng"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Phòng"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ngày Nhận"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Trạng Thái"))
        self.BtnTraPhong.setText(_translate("MainWindow", "Trả Phòng"))
        self.BtnHuy.setText(_translate("MainWindow", "Hủy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Lịch sử/ Trả Phòng"))
        self.BtnAddRoom_5.setText(_translate("MainWindow", "➕ Thêm"))
        self.BtnEditRoom_4.setText(_translate("MainWindow", "✏️ Sửa"))
        self.BtnDeleteRoom_4.setText(_translate("MainWindow", " 🗑 Xóa"))
        self.Search_3.setText(_translate("MainWindow", "🔍 Tìm dịch vụ"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tên Dịch Vụ"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Giá Tiền"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Đơn Vị"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Trạng Thái"))
        self.label_13.setText(_translate("MainWindow", "Thống kê theo"))
        self.label_14.setText(_translate("MainWindow", "Từ ngày"))
        self.label_15.setText(_translate("MainWindow", "Đến ngày"))
        self.BtnXem.setText(_translate("MainWindow", "Xem"))
        self.BtnExcel.setText(_translate("MainWindow", "Xuất Excel"))
        self.BtnPDF.setText(_translate("MainWindow", "Xuất PDF"))
        self.label_17.setText(_translate("MainWindow", "Doanh Thu"))
        self.label_18.setText(_translate("MainWindow", "Phòng Đã Thuê"))
        self.label_19.setText(_translate("MainWindow", "Khách Hàng"))
