# Form implementation generated from reading ui file 'GDLogin.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(359, 304)
        Dialog.setStyleSheet("QLineEdit {\n"
"    padding: 8px;\n"
"    border: 1px solid #D1D5DB;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #2F80ED;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2F80ED;\n"
"    color: white;\n"
"    padding: 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2563EB;\n"
"}\n"
"QWidget {\n"
"    background-color: #F8FAFC;\n"
"}\n"
"QLabel{\n"
"color: black;\n"
"font-weight: bold;\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.BtnLogin = QtWidgets.QPushButton(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BtnLogin.setFont(font)
        self.BtnLogin.setAccessibleDescription("")
        self.BtnLogin.setAutoFillBackground(False)
        self.BtnLogin.setStyleSheet("background: black;")
        self.BtnLogin.setAutoRepeatDelay(300)
        self.BtnLogin.setAutoDefault(True)
        self.BtnLogin.setDefault(False)
        self.BtnLogin.setObjectName("BtnLogin")
        self.verticalLayout.addWidget(self.BtnLogin)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        self.label.setText(_translate("Dialog", "🏨 HOTEL MANAGEMENT SYSTEM"))
        self.label_2.setText(_translate("Dialog", "UserName:"))
        self.label_3.setText(_translate("Dialog", "PassWord:"))
        self.BtnLogin.setText(_translate("Dialog", "Login"))
