# Form implementation generated from reading ui file 'Staff.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StaffWindow(object):
    def setupUi(self, StaffWindow):
        StaffWindow.setObjectName("StaffWindow")
        StaffWindow.resize(1101, 700)
        self.centralwidget = QtWidgets.QWidget(parent=StaffWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, -1, 1101, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SideBar = QtWidgets.QWidget(parent=self.layoutWidget)
        self.SideBar.setMinimumSize(QtCore.QSize(215, 0))
        self.SideBar.setMaximumSize(QtCore.QSize(215, 16777215))
        self.SideBar.setStyleSheet("QWidget {\n"
"    background-color: #1A2A4A;\n"
"  border-right: 2px solid #C9A84C;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"  color: #D0C9B8;\n"
"  font-size: 13px;\n"
"  text-align: left;\n"
"  padding: 11px 20px;\n"
"  border: none;\n"
"  border-left: 3px solid transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #223259;\n"
"  color: #FFFFFF;\n"
"  border-left: 3px solid #C9A84C;\n"
"}\n"
"QPushButton:checked, QPushButton:pressed {\n"
"  background-color: #223259;\n"
"  color: #FFFFFF;\n"
"  border-left: 3px solid #C9A84C;\n"
"  font-weight: bold;\n"
"}\n"
"")
        self.SideBar.setObjectName("SideBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.SideBar)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 211, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #12213A;\n"
"  color: #C9A84C;\n"
"  font-size: 15px;\n"
"  font-weight: bold;\n"
"  padding: 14px 16px;\n"
"  border-bottom: 1px solid #C9A84C;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.SideBar)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 100, 211, 351))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BtnCheckIn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.BtnCheckIn.setCheckable(True)
        self.BtnCheckIn.setObjectName("BtnCheckIn")
        self.verticalLayout_2.addWidget(self.BtnCheckIn)
        self.btnCheckOut = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.btnCheckOut.setCheckable(True)
        self.btnCheckOut.setObjectName("btnCheckOut")
        self.verticalLayout_2.addWidget(self.btnCheckOut)
        self.BtnList = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.BtnList.setCheckable(True)
        self.BtnList.setObjectName("BtnList")
        self.verticalLayout_2.addWidget(self.BtnList)
        self.BtnInvoice = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.BtnInvoice.setObjectName("BtnInvoice")
        self.verticalLayout_2.addWidget(self.BtnInvoice)
        self.BtnService = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.BtnService.setCheckable(True)
        self.BtnService.setObjectName("BtnService")
        self.verticalLayout_2.addWidget(self.BtnService)
        self.BtnAcccount = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.BtnAcccount.setCheckable(True)
        self.BtnAcccount.setObjectName("BtnAcccount")
        self.verticalLayout_2.addWidget(self.BtnAcccount)
        self.horizontalLayout.addWidget(self.SideBar)
        self.widget_2 = QtWidgets.QWidget(parent=self.layoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.TopBar = QtWidgets.QWidget(parent=self.widget_2)
        self.TopBar.setGeometry(QtCore.QRect(0, 0, 881, 52))
        self.TopBar.setMinimumSize(QtCore.QSize(0, 52))
        self.TopBar.setMaximumSize(QtCore.QSize(16777215, 52))
        self.TopBar.setStyleSheet("background-color: #FFFFFF;\n"
"  border-bottom: 2px solid #C9A84C;")
        self.TopBar.setObjectName("TopBar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.TopBar)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 881, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setStyleSheet("color: #1A2A4A;\n"
"  font-size: 16px;\n"
"  font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.SearchBox = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.SearchBox.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.SearchBox.setObjectName("SearchBox")
        self.horizontalLayout_4.addWidget(self.SearchBox)
        self.BtnNotif = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.BtnNotif.setStyleSheet("QPushButton {\n"
"  background-color: #1A2A4A;\n"
"  color: #FFFFFF;\n"
"  border: none;\n"
"  border-radius: 6px;\n"
"  padding: 6px 16px;\n"
"  font-size: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #C9A84C;\n"
"  color: #1A2A4A;\n"
"}")
        self.BtnNotif.setObjectName("BtnNotif")
        self.horizontalLayout_4.addWidget(self.BtnNotif)
        self.BtnLogOut = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.BtnLogOut.setStyleSheet("QPushButton {\n"
"  background-color: #1A2A4A;\n"
"  color: #FFFFFF;\n"
"  border: none;\n"
"  border-radius: 6px;\n"
"  padding: 6px 16px;\n"
"  font-size: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: #C9A84C;\n"
"  color: #1A2A4A;\n"
"}")
        self.BtnLogOut.setObjectName("BtnLogOut")
        self.horizontalLayout_4.addWidget(self.BtnLogOut)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_2)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 50, 881, 601))
        self.stackedWidget.setStyleSheet("background-color: #F7F5F0;\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.CheckInForm = QtWidgets.QFrame(parent=self.page)
        self.CheckInForm.setGeometry(QtCore.QRect(90, 30, 691, 571))
        self.CheckInForm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.CheckInForm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.CheckInForm.setObjectName("CheckInForm")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.CheckInForm)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 671, 553))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_4.setMaximumSize(QtCore.QSize(400, 40))
        self.label_4.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(330, 16777215))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_5.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(330, 16777215))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_7.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_6.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_13.addWidget(self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(330, 16777215))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_13.addWidget(self.lineEdit_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_7 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_7.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_3)
        self.comboBox.setMinimumSize(QtCore.QSize(264, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.comboBox.setStyleSheet("\n"
"QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"    min-width: 240px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_14.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_8 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_8.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_15.addWidget(self.label_8)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.verticalLayoutWidget_3)
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 5px 8px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    border: none;\n"
"    width: 22px;\n"
"}\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_15.addWidget(self.dateEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_9.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=self.verticalLayoutWidget_3)
        self.dateEdit_2.setStyleSheet("QDateEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 5px 8px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    border: none;\n"
"    width: 22px;\n"
"}\n"
"")
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_16.addWidget(self.dateEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_10.setStyleSheet("background-color: #FFFFFF;\n"
"    border: 1.5px solid #C9A84C;\n"
"    border-radius: 4px;\n"
"    color: #1A2B4A;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 6px 12px;\n"
"    min-width: 100px;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_3)
        self.comboBox_2.setMinimumSize(QtCore.QSize(264, 0))
        self.comboBox_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.comboBox_2.setStyleSheet("\n"
"QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"    min-width: 240px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_10.addWidget(self.comboBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem1)
        self.BtnXN = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.BtnXN.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #1A2B4A;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 7px 22px;\n"
"    font-size: 13px;\n"
"    min-width: 110px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E8F5E9;\n"
"    border-color: #3B6D11;\n"
"    color: #3B6D11;\n"
"}")
        self.BtnXN.setObjectName("BtnXN")
        self.horizontalLayout_17.addWidget(self.BtnXN)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(parent=self.page)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(0, 0, 881, 31))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.label_23 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_15)
        self.label_23.setStyleSheet("color: #1A2A4A;\n"
"  font-size: 15px;\n"
"  font-weight: bold;")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_22.addWidget(self.label_23)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 30, 881, 581))
        self.tableWidget.setStyleSheet("QTableWidget, QTableView {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F0EDE6;\n"
"    border: 1px solid #D3CECC;\n"
"    border-radius: 6px;\n"
"    gridline-color: #E5E0D8;\n"
"    selection-background-color: #EAF2FB;\n"
"    selection-color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item, QTableView::item {\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QTableWidget::item:selected, QTableView::item:selected {\n"
"    background-color: #D6E8F7;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 8px 10px;\n"
"    border: none;\n"
"    border-right: 1px solid #223259;\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-right: none;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(parent=self.page_2)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(0, 0, 881, 31))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.label_22 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_14)
        self.label_22.setStyleSheet("color: #1A2A4A;\n"
"  font-size: 15px;\n"
"  font-weight: bold;")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_21.addWidget(self.label_22)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(parent=self.page_3)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(0, 0, 881, 36))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.label_12 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_11)
        self.label_12.setStyleSheet("color: #1A2A4A;\n"
"  font-size: 15px;\n"
"  font-weight: bold;")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem7)
        self.SearchRoom = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_11)
        self.SearchRoom.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 6px 10px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #C9A84C;\n"
"}")
        self.SearchRoom.setObjectName("SearchRoom")
        self.horizontalLayout_18.addWidget(self.SearchRoom)
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.page_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 40, 881, 571))
        self.tableWidget_2.setStyleSheet("QTableWidget, QTableView {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F0EDE6;\n"
"    border: 1px solid #D3CECC;\n"
"    border-radius: 6px;\n"
"    gridline-color: #E5E0D8;\n"
"    selection-background-color: #EAF2FB;\n"
"    selection-color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item, QTableView::item {\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QTableWidget::item:selected, QTableView::item:selected {\n"
"    background-color: #D6E8F7;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 8px 10px;\n"
"    border: none;\n"
"    border-right: 1px solid #223259;\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-right: none;\n"
"}\n"
"")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(parent=self.page_4)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(0, 0, 881, 33))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.label_13 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_12)
        self.label_13.setStyleSheet("color: #1A2A4A;\n"
"  font-size: 15px;\n"
"  font-weight: bold;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_19.addWidget(self.label_13)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.BtnAddService = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_12)
        self.BtnAddService.setStyleSheet("QPushButton {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 7px 18px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton: {\n"
"    background-color: #223259;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0F1B30;\n"
"}")
        self.BtnAddService.setObjectName("BtnAddService")
        self.horizontalLayout_19.addWidget(self.BtnAddService)
        self.tableWidget_3 = QtWidgets.QTableWidget(parent=self.page_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 40, 881, 571))
        self.tableWidget_3.setStyleSheet("QTableWidget, QTableView {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F0EDE6;\n"
"    border: 1px solid #D3CECC;\n"
"    border-radius: 6px;\n"
"    gridline-color: #E5E0D8;\n"
"    selection-background-color: #EAF2FB;\n"
"    selection-color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item, QTableView::item {\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QTableWidget::item:selected, QTableView::item:selected {\n"
"    background-color: #D6E8F7;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 8px 10px;\n"
"    border: none;\n"
"    border-right: 1px solid #223259;\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-right: none;\n"
"}\n"
"")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(parent=self.page_5)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(0, 0, 881, 31))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem10)
        self.label_14 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_13)
        self.label_14.setStyleSheet("color: #1A2A4A;\n"
"  font-size: 15px;\n"
"  font-weight: bold;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_20.addWidget(self.label_14)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem11)
        self.payment_widget = QtWidgets.QWidget(parent=self.page_5)
        self.payment_widget.setGeometry(QtCore.QRect(0, 30, 881, 571))
        self.payment_widget.setObjectName("payment_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.payment_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(parent=self.payment_widget)
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(parent=self.widget)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 851, 171))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.widget1)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #1a2744;\n"
"    border: 1.5px solid #c8952a;\n"
"    border-radius: 6px;\n"
"    margin-top: 10px;\n"
"    padding-top: 8px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 6px;\n"
"    color: #c8952a;\n"
"    background-color: #faf9f5;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(80, 30, 171, 20))
        self.label_15.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 70, 261, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit, QComboBox {\n"
"    border: 1px solid #b0bcd4;\n"
"    border-radius: 4px;\n"
"    padding: 5px 8px;\n"
"    font-size: 12px;\n"
"    background-color: #ffffff;\n"
"    color: #1a2744;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus {\n"
"    border: 1.5px solid #c8952a;\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(250, 130, 93, 28))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #1a2744;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 6px 14px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #243660;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #c8952a;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.widget1)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #1a2744;\n"
"    border: 1.5px solid #c8952a;\n"
"    border-radius: 6px;\n"
"    margin-top: 10px;\n"
"    padding-top: 8px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 6px;\n"
"    color: #c8952a;\n"
"    background-color: #faf9f5;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 401, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Room = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_Room.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"}")
        self.label_Room.setObjectName("label_Room")
        self.gridLayout.addWidget(self.label_Room, 0, 1, 1, 1)
        self.label_Name = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_Name.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"}")
        self.label_Name.setObjectName("label_Name")
        self.gridLayout.addWidget(self.label_Name, 0, 0, 1, 1)
        self.label_CheckIn = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_CheckIn.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"}")
        self.label_CheckIn.setObjectName("label_CheckIn")
        self.gridLayout.addWidget(self.label_CheckIn, 1, 0, 1, 1)
        self.label_CheckOut = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_CheckOut.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"}")
        self.label_CheckOut.setObjectName("label_CheckOut")
        self.gridLayout.addWidget(self.label_CheckOut, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_4.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(parent=self.payment_widget)
        self.widget_3.setObjectName("widget_3")
        self.tableWidget_4 = QtWidgets.QTableWidget(parent=self.widget_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(5, 0, 851, 171))
        self.tableWidget_4.setStyleSheet("QTableWidget, QTableView {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F0EDE6;\n"
"    border: 1px solid #D3CECC;\n"
"    border-radius: 6px;\n"
"    gridline-color: #E5E0D8;\n"
"    selection-background-color: #EAF2FB;\n"
"    selection-color: #1A2B4A;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item, QTableView::item {\n"
"    padding: 6px 10px;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QTableWidget::item:selected, QTableView::item:selected {\n"
"    background-color: #D6E8F7;\n"
"    color: #1A2B4A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 8px 10px;\n"
"    border: none;\n"
"    border-right: 1px solid #223259;\n"
"}\n"
"\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 6px;\n"
"}\n"
"\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-right: none;\n"
"}\n"
"")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(parent=self.payment_widget)
        self.widget_4.setObjectName("widget_4")
        self.widget2 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget2.setGeometry(QtCore.QRect(0, -1, 851, 181))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.widget2)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #1a2744;\n"
"    border: 1.5px solid #c8952a;\n"
"    border-radius: 6px;\n"
"    margin-top: 10px;\n"
"    padding-top: 8px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 6px;\n"
"    color: #c8952a;\n"
"    background-color: #faf9f5;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(parent=self.groupBox_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 421, 151))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_5 = QtWidgets.QWidget(parent=self.verticalLayoutWidget_4)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.widget_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 421, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget_2)
        self.radioButton.setStyleSheet("QRadioButton {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"    spacing: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #c8952a;\n"
"    border: 2px solid #c8952a;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    border: 2px solid #b0bcd4;\n"
"    border-radius: 7px;\n"
"    background-color: #ffffff;\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_5.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget_2)
        self.radioButton_3.setStyleSheet("QRadioButton {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"    spacing: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #c8952a;\n"
"    border: 2px solid #c8952a;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    border: 2px solid #b0bcd4;\n"
"    border-radius: 7px;\n"
"    background-color: #ffffff;\n"
"}")
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_5.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget_2)
        self.radioButton_2.setStyleSheet("QRadioButton {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"    spacing: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #c8952a;\n"
"    border: 2px solid #c8952a;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    border: 2px solid #b0bcd4;\n"
"    border-radius: 7px;\n"
"    background-color: #ffffff;\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_5.addWidget(self.radioButton_2)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.widget_5)
        self.stackedWidget_2.setGeometry(QtCore.QRect(10, 40, 401, 101))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.label_16 = QtWidgets.QLabel(parent=self.page_11)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 131, 20))
        self.label_16.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.page_11)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 40, 211, 22))
        self.lineEdit_5.setStyleSheet("QLineEdit, QComboBox {\n"
"    border: 1px solid #b0bcd4;\n"
"    border-radius: 4px;\n"
"    padding: 5px 8px;\n"
"    font-size: 12px;\n"
"    background-color: #ffffff;\n"
"    color: #1a2744;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus {\n"
"    border: 1.5px solid #c8952a;\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_17 = QtWidgets.QLabel(parent=self.page_11)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.label_17.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.stackedWidget_2.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.stackedWidget_2.addWidget(self.page_12)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.widget2)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #1a2744;\n"
"    border: 1.5px solid #c8952a;\n"
"    border-radius: 6px;\n"
"    margin-top: 10px;\n"
"    padding-top: 8px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 6px;\n"
"    color: #c8952a;\n"
"    background-color: #faf9f5;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(11, 21, 401, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.pushButton_3.setStyleSheet("QPushButtont {\n"
"    background-color: #c8952a;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0a830;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_18.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_19.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"}")
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_21.setStyleSheet("QLabel {\n"
"    font-size: 12px;\n"
"    color: #1a2744;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_20.setStyleSheet("QLabel {\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #c8952a;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #2e7d32;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #388e3c;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(parent=self.page_6)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(0, 0, 881, 31))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem12)
        self.label_24 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_16)
        self.label_24.setStyleSheet("color: #1A2A4A;\n"
"  font-size: 15px;\n"
"  font-weight: bold;")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_23.addWidget(self.label_24)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem13)
        self.ProfileForm = QtWidgets.QFrame(parent=self.page_6)
        self.ProfileForm.setGeometry(QtCore.QRect(200, 70, 471, 471))
        self.ProfileForm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ProfileForm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ProfileForm.setObjectName("ProfileForm")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ProfileForm)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_6 = QtWidgets.QWidget(parent=self.ProfileForm)
        self.widget_6.setObjectName("widget_6")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 301, 41))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: #1a2744;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.widget_6)
        self.lineEdit_6.setGeometry(QtCore.QRect(30, 71, 411, 31))
        self.lineEdit_6.setStyleSheet("QLineEdit, QComboBox {\n"
"    border: 1px solid #b0bcd4;\n"
"    border-radius: 4px;\n"
"    padding: 5px 8px;\n"
"    font-size: 12px;\n"
"    background-color: #ffffff;\n"
"    color: #1a2744;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus {\n"
"    border: 1.5px solid #c8952a;\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_11 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_11.setGeometry(QtCore.QRect(30, 100, 401, 61))
        self.label_11.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: #1a2744;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.widget_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(30, 160, 411, 31))
        self.lineEdit_7.setStyleSheet("QLineEdit, QComboBox {\n"
"    border: 1px solid #b0bcd4;\n"
"    border-radius: 4px;\n"
"    padding: 5px 8px;\n"
"    font-size: 12px;\n"
"    background-color: #ffffff;\n"
"    color: #1a2744;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus {\n"
"    border: 1.5px solid #c8952a;\n"
"}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_7.addWidget(self.widget_6)
        self.widget_8 = QtWidgets.QWidget(parent=self.ProfileForm)
        self.widget_8.setObjectName("widget_8")
        self.label_25 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_25.setGeometry(QtCore.QRect(30, -10, 411, 51))
        self.label_25.setStyleSheet("QLabel {\n"
"    font-size: 14px;\n"
"    color: #1a2744;\n"
"}")
        self.label_25.setObjectName("label_25")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.widget_8)
        self.lineEdit_8.setGeometry(QtCore.QRect(30, 30, 411, 31))
        self.lineEdit_8.setStyleSheet("QLineEdit, QComboBox {\n"
"    border: 1px solid #b0bcd4;\n"
"    border-radius: 4px;\n"
"    padding: 5px 8px;\n"
"    font-size: 12px;\n"
"    background-color: #ffffff;\n"
"    color: #1a2744;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus {\n"
"    border: 1.5px solid #c8952a;\n"
"}")
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.widget_8)
        self.lineEdit_9.setGeometry(QtCore.QRect(30, 71, 411, 31))
        self.lineEdit_9.setStyleSheet("QLineEdit, QComboBox {\n"
"    border: 1px solid #b0bcd4;\n"
"    border-radius: 4px;\n"
"    padding: 5px 8px;\n"
"    font-size: 12px;\n"
"    background-color: #ffffff;\n"
"    color: #1a2744;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus {\n"
"    border: 1.5px solid #c8952a;\n"
"}")
        self.lineEdit_9.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.widget_8)
        self.lineEdit_10.setGeometry(QtCore.QRect(30, 110, 411, 31))
        self.lineEdit_10.setStyleSheet("QLineEdit, QComboBox {\n"
"    border: 1px solid #b0bcd4;\n"
"    border-radius: 4px;\n"
"    padding: 5px 8px;\n"
"    font-size: 12px;\n"
"    background-color: #ffffff;\n"
"    color: #1a2744;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus {\n"
"    border: 1.5px solid #c8952a;\n"
"}")
        self.lineEdit_10.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_8)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 157, 158, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #FFFFFF;\n"
"    color: #1A2B4A;\n"
"    border: 1.5px solid #1A2B4A;\n"
"    border-radius: 5px;\n"
"    padding: 7px 22px;\n"
"    font-size: 13px;\n"
"    min-width: 110px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E8F5E9;\n"
"    border-color: #3B6D11;\n"
"    color: #3B6D11;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_7.addWidget(self.widget_8)
        self.stackedWidget.addWidget(self.page_6)
        self.horizontalLayout.addWidget(self.widget_2)
        StaffWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=StaffWindow)
        self.statusbar.setObjectName("statusbar")
        StaffWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=StaffWindow)
        self.toolBar.setObjectName("toolBar")
        StaffWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.retranslateUi(StaffWindow)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(StaffWindow)

    def retranslateUi(self, StaffWindow):
        _translate = QtCore.QCoreApplication.translate
        StaffWindow.setWindowTitle(_translate("StaffWindow", "StaffWindow"))
        self.label.setText(_translate("StaffWindow", "🏨 HOTEL STAFF"))
        self.BtnCheckIn.setText(_translate("StaffWindow", "🛎 Đặt Phòng"))
        self.btnCheckOut.setText(_translate("StaffWindow", "🚪 Trả Phòng"))
        self.BtnList.setText(_translate("StaffWindow", "🛏  Danh sách phòng"))
        self.BtnInvoice.setText(_translate("StaffWindow", "🧾  Hóa đơn"))
        self.BtnService.setText(_translate("StaffWindow", "⭐  Dịch vụ"))
        self.BtnAcccount.setText(_translate("StaffWindow", "👤  Thông tin cá nhân"))
        self.label_2.setText(_translate("StaffWindow", "Quản Lý Khách Sạn"))
        self.SearchBox.setText(_translate("StaffWindow", "🔍  Tìm kiếm..."))
        self.BtnNotif.setText(_translate("StaffWindow", "🔔"))
        self.BtnLogOut.setText(_translate("StaffWindow", "Đăng xuất"))
        self.label_4.setText(_translate("StaffWindow", "Họ Và Tên Khách Hàng"))
        self.label_5.setText(_translate("StaffWindow", "Số CCCD"))
        self.label_6.setText(_translate("StaffWindow", "Số điện thoại"))
        self.label_7.setText(_translate("StaffWindow", "Chọn phòng"))
        self.label_8.setText(_translate("StaffWindow", "Ngày Đặt Phòng"))
        self.label_9.setText(_translate("StaffWindow", "Ngày Trả Phòng"))
        self.label_10.setText(_translate("StaffWindow", "Dịch Vụ"))
        self.BtnXN.setText(_translate("StaffWindow", "Xác Nhận Đặt Phòng"))
        self.label_23.setText(_translate("StaffWindow", "Đặt Phòng"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("StaffWindow", "Phòng"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("StaffWindow", "Khách Hàng"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("StaffWindow", "Ngày Vào"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("StaffWindow", "Ngày Ra"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("StaffWindow", "Dịch Vụ"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("StaffWindow", "Tổng Tiền"))
        self.label_22.setText(_translate("StaffWindow", "Trả Phòng"))
        self.label_12.setText(_translate("StaffWindow", "Danh Sách Phòng"))
        self.SearchRoom.setText(_translate("StaffWindow", "🔍  Tìm kiếm..."))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("StaffWindow", "Số Phòng"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("StaffWindow", "Loại"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("StaffWindow", "Tầng"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("StaffWindow", "Giá Tiền"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("StaffWindow", "Trạng Thái"))
        self.label_13.setText(_translate("StaffWindow", "Danh Sách Dịch Vụ"))
        self.BtnAddService.setText(_translate("StaffWindow", "➕ Thêm Dịch Vụ"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("StaffWindow", "Phòng"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("StaffWindow", "Dịch Vụ"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("StaffWindow", "Số Lượng"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("StaffWindow", "Đơn Giá"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("StaffWindow", "Thành Tiền"))
        self.label_14.setText(_translate("StaffWindow", "Hóa Đơn Và Thanh Toán"))
        self.groupBox.setTitle(_translate("StaffWindow", "Tìm Hóa Đơn"))
        self.label_15.setText(_translate("StaffWindow", "Số phòng / Tên khách:"))
        self.pushButton.setText(_translate("StaffWindow", "Tìm"))
        self.groupBox_2.setTitle(_translate("StaffWindow", "Thông Tin Khách Hàng"))
        self.label_Room.setText(_translate("StaffWindow", "Phòng:"))
        self.label_Name.setText(_translate("StaffWindow", "Họ Tên:"))
        self.label_CheckIn.setText(_translate("StaffWindow", "CheckIn:"))
        self.label_CheckOut.setText(_translate("StaffWindow", "CheckOut:"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("StaffWindow", "Dịch Vụ"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("StaffWindow", "Số Lượng"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("StaffWindow", "Đơn Giá"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("StaffWindow", "Thành Tiền"))
        self.groupBox_4.setTitle(_translate("StaffWindow", "Phương Thức Thanh Toán"))
        self.radioButton.setText(_translate("StaffWindow", "Tiền Mặt"))
        self.radioButton_3.setText(_translate("StaffWindow", "Chuyển Khoản"))
        self.radioButton_2.setText(_translate("StaffWindow", "Thẻ Ngân Hàng"))
        self.label_16.setText(_translate("StaffWindow", "Khách Đưa:"))
        self.label_17.setText(_translate("StaffWindow", "Tiền Thừa:"))
        self.groupBox_3.setTitle(_translate("StaffWindow", "Tổng Kết"))
        self.pushButton_3.setText(_translate("StaffWindow", "In Hóa Đơn"))
        self.label_18.setText(_translate("StaffWindow", "Tiền Phòng:"))
        self.label_19.setText(_translate("StaffWindow", "Dịch Vụ:"))
        self.label_21.setText(_translate("StaffWindow", "VAT(10%):"))
        self.label_20.setText(_translate("StaffWindow", "Tổng Cộng:"))
        self.pushButton_2.setText(_translate("StaffWindow", "Thanh Toán"))
        self.label_24.setText(_translate("StaffWindow", "Thông Tin Cá Nhân"))
        self.label_3.setText(_translate("StaffWindow", "Họ Tên"))
        self.label_11.setText(_translate("StaffWindow", "Số Điện Thoại"))
        self.label_25.setText(_translate("StaffWindow", "Đổi Mật Khẩu"))
        self.pushButton_4.setText(_translate("StaffWindow", "Cập Nhật"))
        self.toolBar.setWindowTitle(_translate("StaffWindow", "toolBar"))
